name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION

template: |
  ## What’s Changed
  $CHANGES

categories:
- title: ':boom: Breaking Changes'
  labels:
  - breaking-change
- title: ':rocket: Features'
  labels:
  - enhancement
- title: ':wrench: Fixes & Refactoring'
  labels:
  - bug
- title: ':pencil: Documentation'
  labels:
  - documentation
- title: ':arrow_up: Dependencies updates'
  labels:
  - dependencies

version-resolver:
  major:
    labels:
    - breaking-change
  minor:
    labels:
    - enhancement
  patch:
    labels:
    - bug
  default: minor

exclude-labels:
- tech
